### ISSUE TITLE
下载网盘文件  java.io.IOException: open failed: ENAMETOOLONG (File name too long)

### ISSUE THREAD

**Issue by Dminter** [AigeStudio/MultiThreadDownloader#11]
文件名问题 
java.io.IOException: open failed: ENAMETOOLONG (File name too long)
info = new TaskInfo(FileUtil.createFile(dirPath, fileName), url, realUrl, 0, 0);

http://qd.poms.baidupcs.com/file/e1ac32c1d1df39eaa672c2fc7bbc1a36?bkt=p2-nb-722&fid=456079979-250528-847910163939585&time=1444805256&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-%2Fs8xSsBI%2BvfU0ONFZIo8eOnNLTc%3D&to=qb&fm=Nin,B,T,t&sta_dx=0&sta_cs=0&sta_ft=csv&sta_ct=0&fm2=Ningbo,B,T,t&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400e1ac32c1d1df39eaa672c2fc7bbc1a364d09c778000000000024&sl=81395790&expires=1444805856&rt=sh&r=693753015&mlogid=6647443523685284198&sh=1&vuk=-&vbdid=1769361688&fin=gs_%E6%9D%82%E8%B4%A7%E6%B8%85%E5%8D%95.csv&fn=gs_%E6%9D%82%E8%B4%A7%E6%B8%85%E5%8D%95.csv&slt=hlpm&uta=0&rtype=1&iv=0&isw=0&dp-logid=6647443523685284198&dp-callid=0.1.1

**Comment by devaige** [comment]
get!
