### ISSUE TITLE
如果下载的过程中退出应用，该如何保证下次应用启动的时候还能断点续传？

### ISSUE THREAD

**Issue by zhangr011** [AigeStudio/MultiThreadDownloader#15]
在下载的 activity 的 onDestroy 中调用了 dlStop 方法；但是在应用重新启动之后，进行 dlStart 还是重新开始下载的，有没有办法能保证应用重启之后还能继续上次的进度下载？

log 日志有如下记录，但是下载进度还是从 0 开始计算的。

<pre>
11-04 09:44:06.544    8176-8210/com.g17.game.sdzs D/DLManager﹕ http://xxxxxxxxx will be resume.
</pre>

**Comment by devaige** [comment]
退出应用前调用dlStop

**Comment by zhangr011** [comment]
log 日志有如下记录，但是下载进度还是从 0 开始计算的，有没有办法正确的更新下载进度；
另外 dlStop 之后重新开始下载，进度有可能会超过 100 ……

<pre>
11-04 09:44:06.544    8176-8210/com.g17.game.sdzs D/DLManager﹕ http://xxxxxxxxx will be resume.
</pre>

**Comment by zhangr011** [comment]
另外退出时调用 dlStop ，再次打开应用进入 resume 的情况下，下载是无法完成（总是停在 46 的进度不动），再次退出后继续，会出现如下错误：

<pre>
had a unhandled error and it will be restart for new task
</pre>
