### ISSUE TITLE
Number of connection

### ISSUE THREAD

**Issue by siavashabdoli** [AigeStudio/MultiThreadDownloader#18]
where i can find number of connection and thread? I want encrypt data before saving on storage. where i have to edit? and I prefer Only one connection because of my encryption.

**Comment by devaige** [comment]
The best way to encrypt data is get the File when onFinish called, but if you want to encrypt data during transmission, you can encrypt data in [DLThreas](https://github.com/AigeStudio/MultiThreadDownloader/blob/master/Downloader/src/main/java/cn/aigestudio/downloader/bizs/DLThread.java) line 60-64 and [DLTask](https://github.com/AigeStudio/MultiThreadDownloader/blob/master/Downloader/src/main/java/cn/aigestudio/downloader/bizs/DLTask.java) line 221-224

**Comment by siavashabdoli** [comment]
thank you so much. I prefer encrypt during transmission because some of my files are so large. about 100 MB
