### ISSUE TITLE
调用停止后再调用开始下载，下载过来的文件数据不对

### ISSUE THREAD

**Issue by zwstyle** [AigeStudio/MultiThreadDownloader#19]

**Comment by jiahuifu** [comment]
唯一标识是url 

发自我的 iPhone

**Comment by devaige** [comment]
给我看你的下载地址

**Comment by zwstyle** [comment]
我试的几个文件都不行，http://bolome.oss-cn-hangzhou.aliyuncs.com/android/officalsite/boloclient-officalsite_pro-release-2015103020-v2.6-20151104160000.apk，你试下这个链接，反复暂停和开始，返回的数据就不对了，进度也会超过100%，我调试了好久也没有看出是什么原因

**Comment by zwstyle** [comment]
@AigeStudio 是这个下载链接的问题吗？

**Comment by zwstyle** [comment]
目前发现单线程不会出现问题，多线程出现问题

**Comment by zwstyle** [comment]
问题已经找到了，是因为有些服务器对发起的Range格式请求响应数据不一样，有一些服务器必须明确指定下载范围，并且下载范围不能大于文件大小，如果指定下载范围大于文件大小，则返回200，而不是206，目前阿里云的oss服务器就是这样返回的。
在DLTask类的dlDispatch方法中，在计算最后一个线程下载的大小时，多计算了一个字节，导致最后一个线程下载的数据不对，将 end = start + threadLength + remainder; 改为 end = start + threadLength + remainder - 1;便可以正常下载了。
