### ISSUE TITLE
请问如何自定义下载文件的名称呢  

### ISSUE THREAD

**Issue by CNadam** [AigeStudio/MultiThreadDownloader#3]

**Comment by devaige** [comment]
暂且无法自己修改下载文件名，默认文件名以URL中末尾的文件名为主

**Comment by CNadam** [comment]
好的 希望下个版本改进一下 ！

**Comment by kyly1982** [comment]
1.37版不是可以通过修改DLTaskListener中onStart方法的filename然后再调super.onStart来实现自定义名称吗

**Comment by kyly1982** [comment]
可以在onFinish事件中重命名
