### ISSUE TITLE
Please solve the bugs 

### ISSUE THREAD

**Issue by taimur97** [AigeStudio/MultiThreadDownloader#8]
First of all Thanks for this amazing library. 

There are still many bugs so please solve them
Many times it doesn't download files and gives negative values in onProgress sometimes it downloads corrupt files. 
And how can I set threads number. How many threads it uses by default to download files? 
And also please translate the Readme file in English 
Waiting for your reply... 

Thanks :)

**Comment by danog** [comment]
They already have translated it in english.
